// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'media_meta_data.mapper.dart';

@MappableClass()
class MediaMetaData with MediaMetaDataMappable {
  final String url;
  final String format;
  final int height;
  final int width;

  MediaMetaData({
    required this.url,
    required this.format,
    required this.height,
    required this.width,
  });
}
