// required this file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';
import 'package:news_project_saad_faisal_team/network/model/viewed_articles/media.dart';

// Will be generated by dart_mappable
part 'viewed_article.mapper.dart';

@MappableClass()
class ViewedArticle with ViewedArticleMappable {
  final String url;
  @MappableField(key: 'adx_keywords')
  final String adxKeywords;
  final String? column;
  final String section;
  final String byline;
  final String type;
  final String title;
  @MappableField(key: 'published_date')
  final String publishedDate;
  final String source;
  final int id;
  @MappableField(key: 'asset_id')
  final int assetID;
  @MappableField(key: 'des_facet')
  final List<String> desFacet;
  @MappableField(key: 'org_facet')
  final List<String> orgFacet;
  @MappableField(key: 'per_facet')
  final List<String> perFacet;
  @MappableField(key: 'geo_facet')
  final List<String> geoFacet;
  final List<Media> media;
  final String uri;

  ViewedArticle({
    required this.url,
    required this.adxKeywords,
    required this.column,
    required this.section,
    required this.byline,
    required this.type,
    required this.title,
    required this.publishedDate,
    required this.source,
    required this.id,
    required this.assetID,
    required this.desFacet,
    required this.orgFacet,
    required this.perFacet,
    required this.geoFacet,
    required this.media,
    required this.uri,
  });
}
