// this file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';
import 'package:news_project_saad_faisal_team/network/model/viewed_articles/viewed_article.dart';

// Will be generated by dart_mappable
part 'viewed_articles.mapper.dart';

@MappableClass()
class ViewedArticles with ViewedArticlesMappable {
  final String status;
  final String copyright;
  @MappableField(key: 'num_results')
  final int numResults;
  final List<ViewedArticle> results;

  ViewedArticles({
    required this.status,
    required this.copyright,
    required this.numResults,
    required this.results,
  });
}
