// required this file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';
import 'package:news_project_saad_faisal_team/network/model/media_meta/media_meta_data.dart';

// Will be generated by dart_mappable
part 'media.mapper.dart';

@MappableClass()
class Media with MediaMappable {
  final String type;
  final String subtype;
  final String caption;
  final String copyright;
  @MappableField(key: 'approved_for_syndication')
  final bool approvedForSyndication;
  @MappableField(key: 'media-metadata')
  final List<MediaMetaData> mediaMetaData;

  Media({
    required this.type,
    required this.subtype,
    required this.caption,
    required this.copyright,
    required this.approvedForSyndication,
    required this.mediaMetaData,
  });
}
